In [1]:
a = {}

In [3]:
a[1] = {0: 1}

In [7]:
a[1] = {1 : 1} + a[1]

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [6]:
a

{1: {0: 1, 1: 1}}

In [1]:
a = [1, 2, "3"]
print("".join(a))

TypeError: sequence item 0: expected str instance, int found

In [3]:
import tensorflow as tf
import numpy as np

def _create_dataset():
    mnist = tf.keras.datasets.mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    x_train = x_train.reshape(x_train.shape[0], -1)
    x_test = x_test.reshape(x_test.shape[0], -1)
    train_indices = np.where((y_train == 0) | (y_train == 1))[0]
    test_indices = np.where((y_test == 0) | (y_test == 1))[0]
    x_train = x_train[train_indices]
    y_train = y_train[train_indices]
    x_test = x_test[test_indices]
    y_test = y_test[test_indices]
    # データ数が多いので削減
    x_train = x_train[:1000]
    y_train = y_train[:1000]
    return (x_train, y_train), (x_test, y_test)

In [4]:
(x_train, y_train), (x_test, y_test) = _create_dataset()
print(x_train.shape)
print(y_train.shape)

(1000, 784)
(1000,)


In [40]:
a = [0.5, 1, 0.5]
t = y_train[:3]
a = tf.convert_to_tensor(a)
# aをtのshapeに合わせる
a = tf.broadcast_to(a, t.shape)
a = tf.cast(a, tf.float32)
t = tf.convert_to_tensor(t)

In [41]:
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 1. , 0.5], dtype=float32)>

In [42]:
t

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([0, 1, 1], dtype=uint8)>

In [43]:
loss = tf.keras.losses.BinaryCrossentropy(from_logits=False, axis=-1, reduction="none")
-loss(t, a).numpy()

-0.46209797

In [44]:
acc = tf.keras.metrics.BinaryAccuracy()
acc(t, a)

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>